### ISSUE TITLE
pre-reqs documentation

### ISSUE THREAD

**Issue by NickBolles** [scarstens/alfred-workflow-jira-search-utilities#2]
Looks like there are some missing documentation for pre-reqs: 

```
Code 127: /bin/bash: line 3: /usr/local/bin/jq: No such file or directory
```

**Comment by scarstens** [comment]
Ah, good call, I actually was wondering if I missed any dependencies, thanks for taking the time to report this issue.

**Comment by scarstens** [comment]
https://github.com/scarstens/alfred-workflow-jira-search-utilities/pull/4
