### ISSUE TITLE
JSAUTH variable saving with newline in value

### ISSUE THREAD

**Issue by MikeHanSolo** [scarstens/alfred-workflow-jira-search-utilities#3]
Great workflow! 

Encountered a small bug while setting up through the jsconfig workflow steps and noticed that password was being saved with a \n appended at the end. Otherwise the auth works if the character is removed in info.plist for the workflow.

![image](https://user-images.githubusercontent.com/16766209/122455930-8e90ae80-cf72-11eb-9781-a21f25e30c0c.png)

**Comment by scarstens** [comment]
Closing as I'm unable to reproduce the issue.

**Comment by dpidan** [comment]
I also had this issue. The `JSAUTH` variable is getting saved with a line break. 
Easy workaround is to click the [𝒙] ("configure workflow variables") at top-right of workflow editor to remove the line break from the `JSAUTH` value.

Alfred 4
MacOS 10.15.6
