### ISSUE TITLE
Invalid numeric literal at line 13, column 0

### ISSUE THREAD

**Issue by sinewave** [scarstens/alfred-workflow-jira-search-utilities#5]
Hi, just came across this workflow and would love to get it working!

Running into the following error when trying to execute the command "jst fun"

<img width="1067" alt="Alfred server error" src="https://user-images.githubusercontent.com/84384/140699140-d8a66c86-a6f9-47c6-9c6b-729bb301e783.png">

```
[23:12:33.952] JIRA-Server-Utilities-by-Seth[Script Filter] Queuing argument 'fun'
[23:12:34.294] JIRA-Server-Utilities-by-Seth[Script Filter] Script with argv '(null)' finished
[23:12:34.356] ERROR: JIRA-Server-Utilities-by-Seth[Script Filter] Code 4: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2parse error: Invalid numeric literal at line 13, column 0
5381    0 25381    0     0    98k      0 --:--:-- --:--:-- --:--:--   98k
```

**Comment by scarstens** [comment]
Thanks for the report, sadly I no longer have access to JIRA server as we have moved to the cloud.

**Comment by sinewave** [comment]
Oh, ok. Hopefully we'll also move over one of these days!

Any guidance on where to start looking to try and debug this.

**Comment by scarstens** [comment]
the only place it could be is in the JST script filter. if you open the project and click on it, you should see the code in the editor.
```curl "https://${DOMAIN}/rest/api/latest/issue/picker?query={query}&currentJQL=" \
--header "authorization: Basic ${JSAUTH}" \
--http1.1 \
| /usr/local/bin/jq '.sections[0].issues+.sections[1].issues | map({uid: .key, title: .key, subtitle: .summaryText, arg: .key }) | { items: . }'```

Also did you make sure you have JQ installed in your CLI?

**Comment by ibarrajo** [comment]
@sinewave this would probably be fixed by updating the script filter as here:
https://github.com/scarstens/alfred-workflow-jira-search-utilities/issues/6

make sure you have [jq](https://formulae.brew.sh/formula/jq) installed

**Comment by scarstens** [comment]
I modified the code per the suggestion, but I no longer have access to JIRA server to test it. Maybe download the updated version 1.2 and give it a try?

**Comment by sinewave** [comment]
That worked, thanks so much!!
